// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using disser.Models.Base;

#nullable disable

namespace disser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221126101711_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("disser.Models.EF.GOST.GOST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChoisedRukovoditelID")
                        .HasColumnType("integer");

                    b.Property<bool>("OnWork")
                        .HasColumnType("boolean");

                    b.Property<bool>("isFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GOST");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.GOSTKeyWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GOSTID")
                        .HasColumnType("integer");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OtherGOSTId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OtherGOSTId");

                    b.ToTable("GOSTKeyWords");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.OtherGOST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GOSTName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OtherGOST");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.RukovoditelWantWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<int?>("GOSTId")
                        .HasColumnType("integer");

                    b.Property<string>("IspoltitelID")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WorkPercentage")
                        .HasColumnType("double precision");

                    b.Property<bool?>("isFinishedTask")
                        .HasColumnType("boolean");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GOSTId");

                    b.ToTable("RukovoditelWantWork");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.SimilarGOST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedGOSTID")
                        .HasColumnType("integer");

                    b.Property<int?>("GOSTId")
                        .HasColumnType("integer");

                    b.Property<int>("OtherGOSTID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GOSTId");

                    b.ToTable("SimilarGOST");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.UsersGosts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("gostID")
                        .HasColumnType("integer");

                    b.Property<string>("gostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("gostID");

                    b.ToTable("UsersGosts");
                });

            modelBuilder.Entity("disser.Models.EF.Users.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("disser.Models.EF.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LeaderID")
                        .HasColumnType("integer");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isVerify")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.GOSTKeyWords", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.OtherGOST", null)
                        .WithMany("KeyWords")
                        .HasForeignKey("OtherGOSTId");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.RukovoditelWantWork", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.GOST", null)
                        .WithMany("RukovoditelWantWork")
                        .HasForeignKey("GOSTId");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.SimilarGOST", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.GOST", null)
                        .WithMany("similarGOSTs")
                        .HasForeignKey("GOSTId");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.UsersGosts", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.GOST", null)
                        .WithMany("UsersGosts")
                        .HasForeignKey("gostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("disser.Models.EF.Users.Documents", b =>
                {
                    b.HasOne("disser.Models.EF.Users.User", null)
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("disser.Models.EF.GOST.GOST", b =>
                {
                    b.Navigation("RukovoditelWantWork");

                    b.Navigation("UsersGosts");

                    b.Navigation("similarGOSTs");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.OtherGOST", b =>
                {
                    b.Navigation("KeyWords");
                });

            modelBuilder.Entity("disser.Models.EF.Users.User", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
