// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using disser.Models.Base;

#nullable disable

namespace disser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221217053658_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("disser.Models.EF.GOST.AllGOST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedGOSTId")
                        .HasColumnType("integer");

                    b.Property<string>("GOSTName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedGOSTId");

                    b.ToTable("AllGOST");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.CreatedGOST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChoisedRukovoditelID")
                        .HasColumnType("integer");

                    b.Property<bool>("OnWork")
                        .HasColumnType("boolean");

                    b.Property<bool>("isFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GOST");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.RukovoditelWantWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedGOSTId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<string>("IspoltitelID")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WorkPercentage")
                        .HasColumnType("double precision");

                    b.Property<bool?>("isFinishedTask")
                        .HasColumnType("boolean");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedGOSTId");

                    b.ToTable("RukovoditelWantWork");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.SimilarFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GOSTName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimilarFiles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("createdGOSTID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("createdGOSTID");

                    b.ToTable("SimilarFiles");
                });

            modelBuilder.Entity("disser.Models.EF.Users.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("disser.Models.EF.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LeaderID")
                        .HasColumnType("integer");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isVerify")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.AllGOST", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.CreatedGOST", null)
                        .WithMany("AllGOST")
                        .HasForeignKey("CreatedGOSTId");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.RukovoditelWantWork", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.CreatedGOST", null)
                        .WithMany("RukovoditelWantWork")
                        .HasForeignKey("CreatedGOSTId");
                });

            modelBuilder.Entity("disser.Models.EF.GOST.SimilarFile", b =>
                {
                    b.HasOne("disser.Models.EF.GOST.CreatedGOST", null)
                        .WithMany("similarGOSTs")
                        .HasForeignKey("createdGOSTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("disser.Models.EF.Users.Documents", b =>
                {
                    b.HasOne("disser.Models.EF.Users.User", null)
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("disser.Models.EF.GOST.CreatedGOST", b =>
                {
                    b.Navigation("AllGOST");

                    b.Navigation("RukovoditelWantWork");

                    b.Navigation("similarGOSTs");
                });

            modelBuilder.Entity("disser.Models.EF.Users.User", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
